version: '3.3'
services:
  db:
      image: 'mysql:5.6.26'
      container_name: 'mysql_pod'
      environment:
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ROOT_HOST=%
      volumes:
        - mysql-data:/var/lib/mysql
      expose:
        - "3306/tcp"
      networks:
        - default
  api_ppm:
      image: phppm/nginx
      container_name: 'messenger_api_pod'
      command: --debug=1 --bootstrap=symfony --app-env=dev --static-directory=web/
      volumes:
        - ./application/:/var/www
      depends_on:
        - db
      ports:
        - "8080:80"
      networks:
        - default

volumes:
  mysql-data: {}
networks:
  default: {}
