user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation
messenger:
    resource: "@MessengerBundle/Controller"
    type: annotation
    prefix:   /messenger
