user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation

messenger:
    resource: "@MessengerBundle/Resources/config/routing.yml"
    prefix:   /messenger

app.swagger_ui:
    path: /api/doc/messenger
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
