users:
    type:     rest
    resource: 'MessengerBundle\Controller\UsersController'

messages:
    type:     rest
    resource: 'MessengerBundle\Controller\MessagesController'

dialogs:
    type:     rest
    resource: 'MessengerBundle\Controller\DialogsController'
